#  Copyright (c) 2021-2023 NSTDA

{
    "name": "Patient",
    "summary": "Core patient data model, encounters, and encounter management",
    "version": "16.0.0.4.0",
    "development_status": "Alpha",
    "category": "Medical",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": [
        "ni_coding",
        "ni_identifier",
        "ni_period",
        "hr",
        "mail",
        "partner_age",
        "partner_gender",
        "partner_religion",
        "portal",
    ],
    "data": [
        "security/ni_patient_group.xml",
        "security/ni_patient_rules.xml",
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/ir_sequence_data.xml",
        "data/ni_location_type_data.xml",
        "data/ni_encounter_admit_data.xml",
        "data/ni_encounter_arrangement_data.xml",
        "data/ni_encounter_class_data.xml",
        "data/ni_encounter_courtesy_data.xml",
        "data/ni_encounter_diet_data.xml",
        "data/ni_participant_type_data.xml",
        "data/ni_encounter_discharge_disposition_data.xml",
        "data/ni_encounter_discharge_status_data.xml",
        "data/ni_patient_state_reason_data.xml",
        "wizard/ni_encounter_discharge_wizard_views.xml",
        "wizard/ni_patient_archive_wizard_views.xml",
        "views/ni_location_views.xml",
        "views/ni_location_type_views.xml",
        "views/ni_encounter_location_views.xml",
        "views/ni_encounter_participant_views.xml",
        "views/ni_encounter_reason_views.xml",
        "views/ni_encounter_admit_views.xml",
        "views/ni_encounter_arrangement_views.xml",
        "views/ni_encounter_class_views.xml",
        "views/ni_encounter_courtesy_views.xml",
        "views/ni_encounter_diet_views.xml",
        "views/ni_encounter_discharge_views.xml",
        "views/ni_encounter_views.xml",
        "views/ni_participant_type_views.xml",
        "views/res_partner_views.xml",
        "views/res_company_views.xml",
        "views/ni_patient_views.xml",
        "views/ni_workflow_event_views.xml",
        "views/ni_workflow_request_views.xml",
        "views/ni_workflow_line_views.xml",
        "views/ni_patient_portal.xml",
        "views/ni_patient_portal_templates.xml",
        "report/summary_report_templates.xml",
        "report/summary_report.xml",
        "views/ni_patient_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ni_patient/static/src/views/*.js",
            "ni_patient/static/src/views/*.xml",
        ]
    },
    "demo": ["demo/ni_patient_demo.xml", "demo/ni_location_demo.xml"],
    "application": True,
    "auto_install": False,
    "installable": True,
}
