#  Copyright (c) 2021 Piruin P.

{
    "name": "Care Plans",
    "version": "13.0.0.4.0",
    "development_status": "Alpha",
    "category": "Healthcare",
    "author": "Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": ["nirun_patient", "nirun_condition", "mail"],
    "data": [
        "security/careplan_group.xml",
        "security/careplan_rule.xml",
        "security/ir.model.access.csv",
        "data/goal_achievement_data.xml",
        "views/goal_achievement_views.xml",
        "views/goal_code_views.xml",
        "views/careplan_activity_views.xml",
        "views/careplan_activity_code_views.xml",
        "views/careplan_goal_views.xml",
        "views/careplan_category_views.xml",
        "views/careplan_outcome_views.xml",
        "views/careplan_template_views.xml",
        "views/careplan_views.xml",
        "views/patient_views.xml",
        "views/careplan_menus.xml",
        "wizard/careplan_activity_state.xml",
    ],
    "demo": ["data/category_demo.xml"],
    "application": True,
    "auto_install": False,
    "installable": True,
}
