#  Copyright (c) 2021 NSTDA

{
    "name": "Patients",
    "version": "13.0.1.3.0",
    "development_status": "Alpha",
    "category": "Healthcare",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": ["nirun", "hr", "mail", "partner_age", "partner_gender"],
    "data": [
        "data/ir_sequence_data.xml",
        "data/location_type_data.xml",
        "data/encounter_admit_data.xml",
        "data/encounter_arrangement_data.xml",
        "data/encounter_class_data.xml",
        "data/encounter_courtesy_data.xml",
        "data/encounter_diet_data.xml",
        "data/participant_type_data.xml",
        "security/patient_group.xml",
        "security/patient_rules.xml",
        "security/ir.model.access.csv",
        "wizard/discharge_views.xml",
        "views/location_views.xml",
        "views/location_type_views.xml",
        "views/encounter_location_views.xml",
        "views/encounter_reason_views.xml",
        "views/encounter_admit_views.xml",
        "views/encounter_arrangement_views.xml",
        "views/encounter_class_views.xml",
        "views/encounter_courtesy_views.xml",
        "views/encounter_diet_views.xml",
        "views/encounter_discharge_views.xml",
        "views/encounter_views.xml",
        "views/participant_type_views.xml",
        "views/partner_views.xml",
        "views/patient_views.xml",
        "views/patient_menus.xml",
        "views/workflow_event_views.xml",
        "views/workflow_request_views.xml",
    ],
    "demo": ["data/patient_demo.xml", "data/location_demo.xml"],
    "application": True,
    "auto_install": True,
    "installable": True,
}
