#  Copyright (c) 2021 Piruin P.

{
    "name": "Patients",
    "version": "13.0.0.1.0",
    "development_status": "Alpha",
    "category": "Healthcare",
    "author": "Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": ["nirun", "hr", "mail"],
    "data": [
        "data/ir_sequence_data.xml",
        "data/location_data.xml",
        "security/patient_group.xml",
        "security/patient_security.xml",
        "security/ir.model.access.csv",
        "views/location_views.xml",
        "views/patient_views.xml",
        "views/patient_category_views.xml",
        "views/patient_condition.xml",
        "views/patient_condition_latest.xml",
        "views/care_episode_views.xml",
        "views/encounter_views.xml",
        "views/encounter_location_views.xml",
        "views/encounter_reason_views.xml",
        "views/patient_menus.xml",
    ],
    "demo": [
        "data/patient_category_demo.xml",
        "data/patient_demo.xml",
        "data/location_demo.xml",
    ],
    "application": True,
    "auto_install": True,
    "installable": True,
}
