#  Copyright (c) 2023 NSTDA

{
    "name": "Care Plan",
    "summary": "Care planning including goals, services, and outcomes tracking",
    "version": "16.0.0.1.3",
    "development_status": "Alpha",
    "category": "Medical",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": [
        "ni_patient",
        "ni_condition",
        "ni_observation",
        "ni_service",
        "ni_goal",
        "ni_document_ref",
        "ni_medication",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "report/careplan_report.xml",
        "views/ni_careplan_views.xml",
        "views/ni_careplan_category_views.xml",
        "views/ni_encounter_views.xml",
        "views/ni_patient_views.xml",
        "views/ni_goal_achievement_views.xml",
        "views/ni_careplan_template_views.xml",
        "wizard/ni_careplan_wizard_views.xml",
        "views/ni_condition_views.xml",
        "views/ni_careplan_menu.xml",
        "views/res_company_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/ni_careplan/static/src/scss/careplan.scss",
            "ni_careplan/static/src/views/careplan_views.xml",
            "ni_careplan/static/src/views/careplan_views.esm.js",
            "ni_careplan/static/src/scss/careplan_views.scss",
        ],
    },
    "application": False,
    "auto_install": False,
    "installable": True,
}
