#  Copyright (c) 2026 NSTDA

{
    "name": "Immunization",
    "version": "16.0.0.1.0",
    "development_status": "Alpha",
    "category": "Medical",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": ["ni_patient", "ni_body_site"],
    "data": [
        "security/ni_immunization_group.xml",
        "security/ni_immunization_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ni_immunization_route_data.xml",
        "data/ni_immunization_target_disease_data.xml",
        "views/ni_immunization_vaccine_views.xml",
        "views/ni_immunization_route_views.xml",
        "views/ni_immunization_target_disease_views.xml",
        "views/ni_immunization_views.xml",
        "views/ni_immunization_evaluation_views.xml",
        "views/ni_encounter_class_views.xml",
        "views/ni_encounter_views.xml",
        "views/ni_patient_views.xml",
        "views/ni_immunization_menu.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
}
