#  Copyright (c) 2021-2023 NSTDA

{
    "name": "Community Care",
    "summary": "Community-based healthcare services and care management",
    "version": "16.0.0.3.0",
    "development_status": "Alpha",
    "category": "Medical",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": [
        "ni_patient",
        "ni_service",
        "ni_condition",
        "ni_allergy",
        "ni_questionnaire",
        "ni_benefit",
        "l10n_th_ni_patient_address",
        "l10n_th_ni_patient",
        "l10n_th_ni_coverage",
        "ni_related_person",
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "data/ni_patient_type_data.xml",
        "data/ni_condition_categ_data.xml",
        "data/ni_condition_code_data.xml",
        "data/ni_family_relation_data.xml",
        "data/ni_need_data.xml",
        "data/ni_service_event_approval_cron.xml",
        "data/ni_living_with_data.xml",
        "data/ni_relative_benefit_data.xml",
        # "datas/ni_service_categ_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rules_data.xml",
        "views/ni_service_views.xml",
        "views/ni_patient_views.xml",
        "views/ni_cc_report_monthly.xml",
        "views/ni_service_event_view.xml",
        "views/ni_service_category_views.xml",
        "views/ni_need_views.xml",
        "views/ni_family_relation_views.xml",
        "views/ni_patient_type_views.xml",
        "views/ni_patient_need_views.xml",
        "views/ni_risk_assessment_prediction_views.xml",
        "views/ni_risk_assessment_views.xml",
        "views/ni_careplan_view.xml",
        "views/res_users_views.xml",
        "views/hr_employee_view.xml",
        "report/report_paperformat.xml",
        "report/patient_list_report.xml",
        "report/patient_service_report.xml",
        "report/patient_careplan_report.xml",
        "report/service_report.xml",
        "report/event_approval_shared_templates.xml",
        "report/event_approval_service_report.xml",
        "report/event_approval_careplan_report.xml",
        "report/event_approval_elder_report.xml",
        "report/event_approval_category_report.xml",
        "views/ni_service_event_approval_views.xml",
        "views/ni_service_event_report_views.xml",
        "views/res_company_views.xml",
        "views/survey_survey_views.xml",
        "wizard/survey_subject_views.xml",
        "views/ni_patient_smartcard_views.xml",
        "views/ni_living_with_views.xml",
        "views/ni_relative_benefit_views.xml",
        "views/ni_community_care_menu.xml",
        "views/ni_service_event_daily_report_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ni_community_care/static/src/scss/custom.css",
            "ni_community_care/static/src/scss/feedback_icons.css",
            "ni_community_care/static/src/scss/stat_summary.css",
            "ni_community_care/static/src/components/*.js",
            "ni_community_care/static/src/components/*.xml",
            "ni_community_care/static/src/views/*.js",
            "ni_community_care/static/src/views/*.xml",
        ]
    },
    "application": True,
    "auto_install": False,
    "installable": True,
}
