#  Copyright (c) 2026 NSTDA
{
    "name": "Flag",
    "summary": "Prospective warnings and notes about a patient (FHIR Flag resource)",
    "version": "16.0.0.1.0",
    "development_status": "Alpha",
    "category": "Medical",
    "author": "NSTDA, Piruin P.",
    "website": "https://nirun.life/",
    "license": "LGPL-3",
    "maintainers": ["piruin"],
    "depends": ["ni_patient", "ni_period", "ni_identifier"],
    "data": [
        "data/ni_flag_category_data.xml",
        "data/ni_flag_code_data.xml",
        "security/ir.model.access.csv",
        "security/ni_flag_security.xml",
        "data/ir_sequence_data.xml",
        "views/ni_flag_category_views.xml",
        "views/ni_flag_code_views.xml",
        "views/ni_flag_views.xml",
        "views/ni_patient_views.xml",
        "views/ni_encounter_views.xml",
        "views/ni_flag_menu.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
}
