#see https://github.com/pre-commit/action#using-this-action-in-private-repositories
name: pre-commit

on:
  pull_request:
    branches:
      - "13.0*"
  push:
    branches:
      - "13.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
